[theme]
base="light"
primaryColor="#3b82f6"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8fafc"
textColor="#1e293b"

[theme.dark]
base="dark"
primaryColor="#3b82f6"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1e293b"
textColor="#f1f5f9"
